[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    source ~/.config/nvim/plugins/ale.vim
'''
